### ISSUE TITLE
workpool panic when upstream server is closed

### ISSUE THREAD

**Issue by nejisama** [alipay/sofa-mosn#162]
in protocols:
sofarpc-http2，sofarpc-http1， http2-http2

if upstream server is closed, and receive a client request, the mesh will panic

`2018/08/17 17:17:23 [ERROR]worker panic runtime error: invalid memory address or nil pointer dereference
goroutine 11 [running]:
runtime/debug.Stack(0x1, 0x1, 0x16)
	/usr/local/go/src/runtime/debug/stack.go:24 +0xa7
runtime/debug.PrintStack()
	/usr/local/go/src/runtime/debug/stack.go:16 +0x22
github.com/alipay/sofa-mosn/pkg/sync.(*shardWorkerPool).spawnWorker.func1.1(0xc4200562c0, 0xc420056340)
	/Users/neji.bp/Go/src/github.com/alipay/sofa-mosn/pkg/sync/workerpool.go:99 +0xaa
panic(0x192a860, 0x2038350)
	/usr/local/go/src/runtime/panic.go:491 +0x283
github.com/alipay/sofa-mosn/pkg/proxy.(*upstreamRequest).appendData(0xc4201b0180, 0x1ff4fc0, 0xc42039a150, 0xc42039a101)
	/Users/neji.bp/Go/src/github.com/alipay/sofa-mosn/pkg/proxy/upstream.go:155 +0x7a
github.com/alipay/sofa-mosn/pkg/proxy.(*downStream).doReceiveData(0xc4203a8160, 0x0, 0x1ff4fc0, 0xc42039a150, 0xc42018da01)
	/Users/neji.bp/Go/src/github.com/alipay/sofa-mosn/pkg/proxy/downstream.go:339 +0xd5
github.com/alipay/sofa-mosn/pkg/proxy.(*downStream).ReceiveData(0xc4203a8160, 0x1ff4fc0, 0xc42039a150, 0x1)
	/Users/neji.bp/Go/src/github.com/alipay/sofa-mosn/pkg/proxy/downstream.go:325 +0xce
github.com/alipay/sofa-mosn/pkg/proxy.eventProcess(0x2, 0xc420380ec8, 0x1910560, 0xc420394140)
	/Users/neji.bp/Go/src/github.com/alipay/sofa-mosn/pkg/proxy/event.go:142 +0x3b6
github.com/alipay/sofa-mosn/pkg/proxy.eventDispatch(0x2, 0xc42005e240)
	/Users/neji.bp/Go/src/github.com/alipay/sofa-mosn/pkg/proxy/event.go:85 +0x102
github.com/alipay/sofa-mosn/pkg/sync.(*shardWorkerPool).spawnWorker.func1(0xc4200562c0, 0xc420056340)
	/Users/neji.bp/Go/src/github.com/alipay/sofa-mosn/pkg/sync/workerpool.go:107 +0x75
created by github.com/alipay/sofa-mosn/pkg/sync.(*shardWorkerPool).spawnWorker
	/Users/neji.bp/Go/src/github.com/alipay/sofa-mosn/pkg/sync/workerpool.go:95 +0x49
`

**Comment by nejisama** [comment]
fix by #163
