### ISSUE TITLE
Make image  wrong with install supervisor, need python7

### ISSUE THREAD

**Issue by xiaoxi1989** [alipay/sofa-mosn#633]
### Describe the bug

`RUN easy_install supervisor`

```
sh-4.1# easy_install supervisor
Searching for supervisor
Reading https://pypi.douban.com/simple/supervisor/
Best match: supervisor 4.0.1
Downloading https://pypi.doubanio.com/packages/96/ec/f8190beeb0c6d29a30aea10389c11d0164b6ff221931ee84093315ecde6a/supervisor-4.0.1.tar.gz#md5=a786a274c7f01d493e924068d216c024
Processing supervisor-4.0.1.tar.gz
Running supervisor-4.0.1/setup.py -q bdist_egg --dist-dir /tmp/easy_install-aLS1e3/supervisor-4.0.1/egg-dist-tmp-7s1IiQ
Traceback (most recent call last):
  File "/usr/bin/easy_install", line 9, in <module>
    load_entry_point('distribute==0.6.10', 'console_scripts', 'easy_install')()
  File "/usr/lib/python2.6/site-packages/setuptools/command/easy_install.py", line 1715, in main
    with_ei_usage(lambda:
  File "/usr/lib/python2.6/site-packages/setuptools/command/easy_install.py", line 1696, in with_ei_usage
    return f()
  File "/usr/lib/python2.6/site-packages/setuptools/command/easy_install.py", line 1719, in <lambda>
    distclass=DistributionWithoutHelpCommands, **kw
  File "/usr/lib64/python2.6/distutils/core.py", line 152, in setup
    dist.run_commands()
  File "/usr/lib64/python2.6/distutils/dist.py", line 975, in run_commands
    self.run_command(cmd)
  File "/usr/lib64/python2.6/distutils/dist.py", line 995, in run_command
    cmd_obj.run()
  File "/usr/lib/python2.6/site-packages/setuptools/command/easy_install.py", line 236, in run
    self.easy_install(spec, not self.no_deps)
  File "/usr/lib/python2.6/site-packages/setuptools/command/easy_install.py", line 472, in easy_install
    return self.install_item(spec, dist.location, tmpdir, deps)
  File "/usr/lib/python2.6/site-packages/setuptools/command/easy_install.py", line 502, in install_item
    dists = self.install_eggs(spec, download, tmpdir)
  File "/usr/lib/python2.6/site-packages/setuptools/command/easy_install.py", line 681, in install_eggs
    return self.build_and_install(setup_script, setup_base)
  File "/usr/lib/python2.6/site-packages/setuptools/command/easy_install.py", line 958, in build_and_install
    self.run_setup(setup_script, setup_base, args)
  File "/usr/lib/python2.6/site-packages/setuptools/command/easy_install.py", line 947, in run_setup
    run_setup(setup_script, args)
  File "/usr/lib/python2.6/site-packages/setuptools/sandbox.py", line 29, in run_setup
    lambda: execfile(
  File "/usr/lib/python2.6/site-packages/setuptools/sandbox.py", line 70, in run
    return func()
  File "/usr/lib/python2.6/site-packages/setuptools/sandbox.py", line 31, in <lambda>
    {'__file__':setup_script, '__name__':'__main__'}
  File "setup.py", line 21, in <module>
RuntimeError: On Python 2, Supervisor requires Python 2.7 or later
```

### Environment
+ SOFAMosn Version
master

### Suggest
easy_install supervisor==3.X.X

**Comment by ldxdl** [comment]
@xiaoxi1989 感谢指出问题，镜像化方案已集成到sofamesh中，请查看setup文档：https://github.com/alipay/sofa-mosn/blob/master/docs/quickstart/Setup.md
@nejisama 请修复此问题，指定supervisor为3.x.x版本或指定upgrade py，考虑到4.x版本supervisor我们没有验证过，建议使用第一种方式先修复

**Comment by nejisama** [comment]
@xiaoxi1989 指定了version为3.4.0 目前在分支fix_supervisor_ver 可以验证一下是否OK了
